service: serverless-aws-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  getProductsList:
    handler: functions/getProductsList.getProductsList
    environment:
      TABLE_NAME: AWS_PRODUCTS_TABLE
    events:
      - http:
          path: products
          method: get
  getProductsById:
    handler:  functions/getProductsById.getProductsById
    environment:
      TABLE_NAME: AWS_PRODUCTS_TABLE
    events:
      - http:
          path: /products/{productId}
          method: get
  insertData:
    handler: functions/insertData.insertData
    environment:
      TABLE_NAME: AWS_PRODUCTS_TABLE
  createProduct:
    handler: functions.createProduct.createProduct
    environment:
      TABLE_NAME: AWS_PRODUCTS_TABLE
    events:
      - http:
          method: post
          path: products